# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "Y:/tmp/cop410/programming/simExtOMPL/build/ompl-1.5.0-prefix/src/ompl-1.5.0;Y:/tmp/cop410/programming/simExtOMPL/build/ompl-1.5.0-prefix/src/ompl-1.5.0-build")
set(CPACK_CMAKE_GENERATOR "MinGW Makefiles")
set(CPACK_COMPONENTS_ALL "ompl;python;morse")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_MORSE_DEPENDS "python")
set(CPACK_COMPONENT_MORSE_DESCRIPTION "The Blender/MORSE plugin allows one to plan paths using the MORSE robot simulator. MORSE is built on top of Blender and uses its built-in physics engine to compute physically realistic motions.")
set(CPACK_COMPONENT_MORSE_DISPLAY_NAME "Blender/MORSE plugin")
set(CPACK_COMPONENT_OMPL_DISPLAY_NAME "OMPL library, headers, and demos")
set(CPACK_COMPONENT_OMPL_REQUIRED "ON")
set(CPACK_COMPONENT_PYTHON_DEPENDS "ompl")
set(CPACK_COMPONENT_PYTHON_DISPLAY_NAME "Python bindings")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/2021fall/compile_copsim_for_cad2021/data/msys64_20210419/mingw64/share/cmake-3.20/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "ompl built using CMake")
set(CPACK_GENERATOR "TGZ;ZIP")
set(CPACK_IGNORE_FILES "/.vscode;/build/;.pyc$;.pyo$;__pycache__;.so$;.dylib$;.orig$;.log$;.DS_Store;/html/;/bindings/;TODO;.registered$;binding_generator.py$")
set(CPACK_INSTALLED_DIRECTORIES "Y:/tmp/cop410/programming/simExtOMPL/build/ompl-1.5.0-prefix/src/ompl-1.5.0;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/ompl")
set(CPACK_MODULE_PATH ";/cmake/Modules;Y:/tmp/cop410/programming/simExtOMPL/build/ompl-1.5.0-prefix/src/ompl-1.5.0/CMakeModules")
set(CPACK_NSIS_DISPLAY_NAME "ompl 1.5.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "ompl 1.5.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "Y:/tmp/cop410/programming/simExtOMPL/build/ompl-1.5.0-prefix/src/ompl-1.5.0-build/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "Mark Moll <mmoll@rice.edu>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/2021fall/compile_copsim_for_cad2021/data/msys64_20210419/mingw64/share/cmake-3.20/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "The Open Motion Planning Library (OMPL)")
set(CPACK_PACKAGE_FILE_NAME "ompl-1.5.0-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "ompl 1.5.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "ompl 1.5.0")
set(CPACK_PACKAGE_NAME "ompl")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Rice University")
set(CPACK_PACKAGE_VERSION "1.5.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "5")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "C:/2021fall/compile_copsim_for_cad2021/data/msys64_20210419/mingw64/share/cmake-3.20/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "C:/2021fall/compile_copsim_for_cad2021/data/msys64_20210419/mingw64/share/cmake-3.20/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/2021fall/compile_copsim_for_cad2021/data/msys64_20210419/mingw64/share/cmake-3.20/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/.vscode;/build/;.pyc$;.pyo$;__pycache__;.so$;.dylib$;.orig$;.log$;.DS_Store;/html/;/bindings/;TODO;.registered$;binding_generator.py$")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "Y:/tmp/cop410/programming/simExtOMPL/build/ompl-1.5.0-prefix/src/ompl-1.5.0;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "Y:/tmp/cop410/programming/simExtOMPL/build/ompl-1.5.0-prefix/src/ompl-1.5.0-build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "ompl-1.5.0-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "Y:/tmp/cop410/programming/simExtOMPL/build/ompl-1.5.0-prefix/src/ompl-1.5.0-build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
